using Microsoft.AspNetCore.Http;
using Microsoft.Net.Http.Headers;

namespace CaseMngmt.Service.Invoices
{
    // Minimal IFormFile wrapper so a Service (not an HTTP request) can pass generated bytes
    // (e.g. a QuestPDF invoice) into FileUploadService.UploadEntityFileAsync, which only
    // ever calls CopyTo/CopyToAsync on the IFormFile it receives.
    public class InMemoryFormFile : IFormFile
    {
        private readonly byte[] _content;

        public InMemoryFormFile(byte[] content, string fileName, string contentType)
        {
            _content = content;
            FileName = fileName;
            Name = fileName;
            ContentType = contentType;
            Headers = new HeaderDictionary();
            ContentDisposition = new ContentDispositionHeaderValue("form-data")
            {
                Name = Name,
                FileName = FileName
            }.ToString();
        }

        public string ContentType { get; }
        public string ContentDisposition { get; }
        public IHeaderDictionary Headers { get; }
        public long Length => _content.Length;
        public string Name { get; }
        public string FileName { get; }

        public void CopyTo(Stream target) => OpenReadStream().CopyTo(target);

        public Task CopyToAsync(Stream target, CancellationToken cancellationToken = default) =>
            OpenReadStream().CopyToAsync(target, cancellationToken);

        public Stream OpenReadStream() => new MemoryStream(_content, writable: false);
    }
}
