// <auto-generated />
using CaseMngmt.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaseMngmt.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731000002_AddEntityKeywordTable")]
    partial class AddEntityKeywordTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
